import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PortFolio PRANAV',
  description: 'Generated by Pranav',
}

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: '100'
})



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script src="" />
    </html>
  )
}
